eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost
server:
  port: 8761
# spring:
#       cloud:
#         config:
#             server:
#                 git:
#                     uri: https://github.com/jit9628/microservices-configuration-server.git
